backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

locale: 'es'

collections:
  - name: "data"
    label: "Configuración"
    delete: false
    editor:
      preview: false
    files:
      - name: "catalog"
        label: "Catálogo de Servicios"
        file: "catalog.json"
        fields:
          - label: "Lista de Servicios"
            name: "services"
            widget: "list"
            summary: '{{fields.name}} - {{fields.price}}'
            fields:
              - { label: "ID Único (Número)", name: "id", widget: "number", value_type: "int" }
              - { label: "Nombre del Servicio", name: "name", widget: "string" }
              - { label: "Descripción", name: "desc", widget: "text" }
              - { label: "Precio ($)", name: "price", widget: "number", value_type: "int" }
              - { label: "Categoría", name: "category", widget: "select", options: ["Cortes", "Barba", "Color", "Tratamientos"] }
              - { label: "Imagen del Servicio", name: "image", widget: "image", required: false }